/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tour;

import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class tour_customer_selecte_location extends javax.swing.JFrame {

    /**
     * Creates new form tour_customer_selecte_location
     */
    
    
      Connection con = null;
    PreparedStatement pst = null; 
    ResultSet rs = null ; 
    
    public tour_customer_selecte_location() {
        initComponents();
         con = DBconnect.connect();
         
    }

    
   String c_para ; 
   String c_mame ;
   String c_p_name ; 
   String cs_date;
   String ce_date;
   
    
    public tour_customer_selecte_location(String s_date ,String e_date ,int para , String p_name ,String c_id) {
        initComponents();
         con = DBconnect.connect();
   /*  System.out.println(s_date);
     System.out.println(e_date);*/
     
     
         cs_date =s_date;
         ce_date =e_date;
     
     
     jLabel20.setText(p_name);
     c_p_name =p_name ; 
       
     c_para = Integer.toString(para);  
     table();
        get_cost_location();
        avg_cost() ; 
        
           c_mame =   c_id ; 
           
           // set value lable 
           
            tour_customer_oop re = new tour_customer_oop();
          jLabel15.setText(re.table2_car());
            jLabel22.setText(re.set_guider_count());
           
           
     
    }
    
    
    int selecttion_count =  1 ; 
    String cost_covert  ;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    String location_1 ;
    String location_2 ;
    String location_3 ;
    String location_4 ;
    String location_5 ;
    String location_6 ;
    String location_7 ;
    String location_8 ;
    String location_9 ;
    String location_10 ;

  /* tour_customer_selecte_location(String Cpackage_id, String Cp_name, String Cc_id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
    
    
    public void table(){
        
        
         String sql = " select id ,location_1,location_2,location_3,location_4,location_5,location_6,location_7,location_8,location_9,location_10  from it160_package_location_history where package_ID   like  '"+c_para+"'"  ;
        
        
          try {
              int loopnumber =0;
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql);
              
              
              
             while (rs.next()) {
              int id = rs.getInt("id");
          location_1 = rs.getString("location_1");
          location_2 = rs.getString("location_2");
          location_3 = rs.getString("location_3");
          location_4 = rs.getString("location_4");
          location_5 = rs.getString("location_5");
         location_6 = rs.getString("location_6");
          location_7 = rs.getString("location_7");
          location_8 = rs.getString("location_8");
         location_9 = rs.getString("location_9");
         location_10 = rs.getString("location_10");
        
         
         jCheckBox2.setText(location_1);
            jCheckBox3.setText(location_2);
            jCheckBox4.setText(location_3);
            jCheckBox5.setText(location_4);
            jCheckBox6.setText(location_5);
            jCheckBox7.setText(location_6);
            jCheckBox8.setText(location_7);
            jCheckBox9.setText(location_8);
            jCheckBox1.setText(location_9);
             
             
             
             }
              
          } catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
    
    
         int location_cost1 ;
           int location_cost2 ;
             int location_cost3 ;
               int location_cost4 ;
                 int location_cost5 ;
                   int location_cost6 ;
                     int location_cost7 ;
                       int location_cost8 ;
                         int location_cost9 ;
                           int location_cost10 ;
    
    public void get_cost_location(){
         
          try {
              String sql_1 = "select cost from place where  name like '"+location_1+"'"  ;
              
              
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
     
              while (rs.next()) {
                  
                   location_cost1 = rs.getInt("cost");
            //        System.out.println(location_cost1) ;
              
              }
                      
               } 
          
             catch (SQLException ex) {
             Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    
      //***********************************************************************************************    
          try {
          String sql_1 = "select cost from place where  name like '"+location_2+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost2 = rs.getInt("cost");
                //   System.out.println(location_cost2) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_3+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost3 = rs.getInt("cost");
            //        System.out.println(location_cost3) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                  
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_4+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost4 = rs.getInt("cost");
             //       System.out.println(location_cost4) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                        
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_5+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost5 = rs.getInt("cost");
           //         System.out.println(location_cost5) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                        
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_6+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost6 = rs.getInt("cost");
          //         System.out.println(location_cost6) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                        
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_7+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost7 = rs.getInt("cost");
           //       System.out.println(location_cost7) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                        
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_8+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost8 = rs.getInt("cost");
          //          System.out.println(location_cost8) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                        
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_9+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost9 = rs.getInt("cost");
            //     System.out.println(location_cost9) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
                        
       //******************************************************************************************     
            
                try {
          String sql_1 = "select cost from place where  name like '"+location_10+"'"  ;
              
            
              Statement stmt = con.createStatement();
              rs = stmt.executeQuery(sql_1);
          
                 while (rs.next()) {
                  
                   location_cost10 = rs.getInt("cost");
              //    System.out.println(location_cost10) ;
              
              }
              
              
              }
          
          
                catch (SQLException ex) {
              Logger.getLogger(tour_customer_selecte_location.class.getName()).log(Level.SEVERE, null, ex);
          }
            
      
          
    }
    
    float avg_package_cost =  0 ; 
    
    public void avg_cost(){
        
        
     avg_package_cost =    location_cost1 + location_cost1 +location_cost1 +location_cost1 +location_cost1 +location_cost1 +location_cost1 +location_cost1 +location_cost1 + location_cost1 ; 
        avg_package_cost = (float) (avg_package_cost * 0.70) ; 
       // System.out.println(avg_package_cost);
       
       cost_covert = Float.toString(avg_package_cost) ;
       jLabel34.setText(cost_covert);
         
         
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/U9.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(980, 510, 310, 150);

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/m1.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 120, 310, 150);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("you can only select 6 locations from here. If you add more than 6 locations, each location will charge an additional cost");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 90, 750, 30);

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/l3.jpg"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 320, 310, 150);

        jLabel6.setBackground(new java.awt.Color(0, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/U3.jpg"))); // NOI18N
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(640, 320, 310, 150);

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/U8.jpg"))); // NOI18N
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(640, 120, 310, 150);

        jLabel10.setBackground(new java.awt.Color(0, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/U11.jpg"))); // NOI18N
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(980, 320, 310, 150);

        jLabel12.setBackground(new java.awt.Color(0, 51, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/U10.jpg"))); // NOI18N
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(300, 510, 310, 150);

        jLabel13.setBackground(new java.awt.Color(0, 51, 51));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/l1.jpg"))); // NOI18N
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(640, 510, 310, 150);

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(" Back to Package");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25);
        jLabel25.setBounds(280, 10, 170, 100);

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuor_image/U5.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(980, 120, 310, 150);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RS:");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1090, 30, 50, 40);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(450, 10, 10, 90);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(1020, 10, 20, 110);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("package name");
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(560, 20, 300, 50);

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(1090, 670, 110, 25);

        jCheckBox2.setText("jCheckBox1");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(380, 280, 120, 25);

        jCheckBox3.setText("jCheckBox1");
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(720, 280, 120, 25);

        jCheckBox4.setText("jCheckBox1");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(1080, 280, 120, 25);

        jCheckBox5.setText("jCheckBox1");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(390, 480, 140, 25);

        jCheckBox6.setText("jCheckBox1");
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(720, 480, 130, 25);

        jCheckBox7.setText("jCheckBox1");
        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(1090, 480, 120, 25);

        jCheckBox8.setText("jCheckBox1");
        jCheckBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox8MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(370, 670, 130, 25);

        jCheckBox9.setText("jCheckBox1");
        jCheckBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox9MouseEntered(evt);
            }
        });
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(730, 670, 120, 25);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("300");
        jLabel34.setOpaque(true);
        jPanel1.add(jLabel34);
        jLabel34.setBounds(1150, 30, 140, 40);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 150, 130, 2);

        jLabel15.setBackground(new java.awt.Color(0, 0, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("5");
        jLabel15.setOpaque(true);
        jPanel2.add(jLabel15);
        jLabel15.setBounds(190, 450, 40, 29);

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Negombo");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(80, 230, 80, 40);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Inn");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(90, 90, 170, 20);

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Dashboard");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(30, 300, 170, 29);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Guider");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(30, 500, 50, 30);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Available location");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(20, 410, 140, 29);

        jLabel22.setBackground(new java.awt.Color(0, 0, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("?");
        jLabel22.setOpaque(true);
        jPanel2.add(jLabel22);
        jLabel22.setBounds(190, 500, 40, 29);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 560, 210, 10);

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Next");
        jLabel23.setOpaque(true);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel23);
        jLabel23.setBounds(40, 610, 130, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 600, 150, 50);

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Packages");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 370, 100, 29);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(10, 340, 100, 20);

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("The");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(10, 10, 170, 20);

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Terrnova");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(30, 40, 220, 40);

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Vailable car");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(0, 460, 130, 29);

        jLabel28.setBackground(new java.awt.Color(0, 0, 204));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("4");
        jLabel28.setOpaque(true);
        jPanel2.add(jLabel28);
        jLabel28.setBounds(190, 370, 40, 29);

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Welcome to Terrnova Inn");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(40, 170, 230, 40);

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("We Provide the Best Services in ");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(30, 200, 230, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 270, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void set_location(){
    
        
    }
    
    
    
    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

      
    String p_location_1 ;
    String p_location_2 ;
    String p_location_3 ;
    String p_location_4 ;
    String p_location_5 ;
    String p_location_6 ;
    String p_location_7 ;
    String p_location_8 ;
    String p_location_9 ;
    String p_location_10 ;
    
    
        float set_loacation_count_1 = 2; 
    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
 
        if(set_loacation_count_1 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_1=5;
     // System.out.println(selecttion_count) ;
       p_location_1 =  jCheckBox2.getText();

           }
           
           else {
                    set_loacation_count_1++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost1 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_1 =  jCheckBox2.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_1% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost1 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_1 ="";
                          set_loacation_count_1 = 2 ;
                            
        
    }
         //  System.out.println(p_location_1);
           
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2MouseClicked

    float set_loacation_count_2 = 2;
    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked

         if(set_loacation_count_2 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_2=5;
     // System.out.println(selecttion_count) ;
       p_location_2 =  jCheckBox3.getText();

           }
           
           else {
                    set_loacation_count_2++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost2 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_2 =  jCheckBox3.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_2% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost2 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_2 ="*";
                          set_loacation_count_2 = 2 ;
                            
        
    }
        //   System.out.println(location_cost2);
           
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3MouseClicked

    
    float set_loacation_count_3 = 2;
    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked

                
                
                  if(set_loacation_count_3 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_3=5;
     // System.out.println(selecttion_count) ;
       p_location_3 =  jCheckBox4.getText();

           }
           
           else {
                    set_loacation_count_3++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost3 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_3 =  jCheckBox4.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_3% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost3 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_3 ="";
                          set_loacation_count_3 = 2 ;
                            
        
    }
       //    System.out.println(p_location_3);
           
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4MouseClicked

    float set_loacation_count_4 = 2;
    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked

                        
                  if(set_loacation_count_4 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_4=5;
     // System.out.println(selecttion_count) ;
       p_location_4 =  jCheckBox5.getText();

           }
           
           else {
                    set_loacation_count_4++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost4 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_4 =  jCheckBox5.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_4% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost4 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_4 ="";
                          set_loacation_count_4 = 2 ;
                            
        
    }
        //  System.out.println(p_location_4);
           
       


        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5MouseClicked

        float set_loacation_count_5 = 2 ; 
    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked

                      
                  if(set_loacation_count_5 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_5=5;
     // System.out.println(selecttion_count) ;
       p_location_5 =  jCheckBox6.getText();

           }
           
           else {
                    set_loacation_count_5++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost5 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_5 =  jCheckBox6.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_5% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost5 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_5 ="";
                          set_loacation_count_5 = 2 ;
                            
        
    }
          //System.out.println(p_location_5);
           
       


        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6MouseClicked

        float set_loacation_count_6  = 2 ; 
    private void jCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseClicked
           
                  if(set_loacation_count_6 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_6=5;
     // System.out.println(selecttion_count) ;
       p_location_6 =  jCheckBox7.getText();

           }
           
           else {
                    set_loacation_count_6++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost6 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_6 =  jCheckBox7.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_6% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost6 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_6 ="";
                          set_loacation_count_6 = 2 ;
                            
        
    }
          //System.out.println(p_location_6);
           
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7MouseClicked
        float set_loacation_count_7  = 2 ; 
    private void jCheckBox8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox8MouseClicked

               if(set_loacation_count_7 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_7=5;
     // System.out.println(selecttion_count) ;
       p_location_7 =  jCheckBox8.getText();

           }
           
           else {
                    set_loacation_count_7++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost7 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_7 =  jCheckBox8.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_7% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost7 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_7 ="";
                          set_loacation_count_7 = 2 ;
                            
        
    }
          //System.out.println(p_location_7);
           
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8MouseClicked
        float set_loacation_count_8 = 2 ; 
    private void jCheckBox9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox9MouseClicked

                  if(set_loacation_count_8 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_8=5;
     // System.out.println(selecttion_count) ;
       p_location_8 =  jCheckBox9.getText();

           }
           
           else {
                    set_loacation_count_8++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost8 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_8 =  jCheckBox9.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_8% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost8 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_8 ="";
                          set_loacation_count_8 = 2 ;
                            
        
    }
       //   System.out.println(p_location_8);
           
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9MouseClicked
 float set_loacation_count_9 = 2 ; 
    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked

                  if(set_loacation_count_9 % 2 == 0){
           if(selecttion_count <= 6 ){
        selecttion_count++ ; 
        set_loacation_count_9=5;
     // System.out.println(selecttion_count) ;
       p_location_9 =  jCheckBox1.getText();

           }
           
           else {
                    set_loacation_count_9++;
                    JFrame parent = new JFrame();

                     JOptionPane.showMessageDialog(parent, "You can only add 6 Locations,  \n" + " Else it will costs more than the current cost"); 
        
                         
                                        avg_package_cost= avg_package_cost  + location_cost9 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_9 =  jCheckBox1.getText();
                          
           }
           
    
           }
        else if (set_loacation_count_9% 2 == 1) {
            
             avg_package_cost= avg_package_cost  - location_cost9 ;  
                                           cost_covert = Float.toString(avg_package_cost) ;
                          jLabel34.setText(cost_covert); 
                          p_location_9 ="";
                          set_loacation_count_9 = 2 ;
                            
        
    }
       //   System.out.println(p_location_8);

            // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked

            tour_customer_select_package_2 ll = new tour_customer_select_package_2(cs_date,ce_date,c_mame);
              ll.setVisible(true);
                this.dispose();
            

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked


        tour_customer_select_vehicle lp = new tour_customer_select_vehicle( cs_date,ce_date,avg_package_cost ,c_para ,  c_p_name ,  c_mame ,p_location_1 ,p_location_2 , p_location_3 ,p_location_4 , p_location_5 , p_location_6 , p_location_7 ,p_location_8 ,p_location_9 ,p_location_10) ; 
      lp.setVisible(true);
        this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jCheckBox9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tour_customer_selecte_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tour_customer_selecte_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tour_customer_selecte_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tour_customer_selecte_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tour_customer_selecte_location().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
